### PR TITLE
Implementing strict matching for regexes and fixed deletion of "replicate-to" resources

### LINKED ISSUE #48: Namespace regexes match substrings
**Describe the bug**
When a secret is configured with a regex for matching allowed replication targets (for example, using an annotation like `replicator.v1.mittwald.de/replication-allowed-namespaces: "namespace-[0-9]*"`), the regex will also match substrings of the namespace name. This means that `foonamespace-123bar` will also be matched by `namespace-[0-9]*`.

**To Reproduce**
1. Create a secret with `replicator.v1.mittwald.de/replication-allowed-namespaces: "bar"`
2. Create a namespace `foobarbaz`
3. Create a secret within that namespace and replicate from the original secret
4. Profit!

**Expected behavior**
Secret should not be replicated. Or should it!? 🤔 

**Environment:**
 - Kubernetes version: irrelevant
 - kubernetes-replicator version: v2.3.0

**Additional context**
Credits to @bokysan for discovering this issue in #47

### PR DESCRIPTION
**Pull request by YannikBramkamp**
fixes #48

### CODE REVIEW

**Comment by YannikBramkamp** [comment]
fixes #65

File: replicate/configmap/configmaps.go [hunk 1]
```diff
@@ -272,7 +272,7 @@ func (r *Replicator) DeleteReplicatedResource(targetResource interface{}) error
 
 	if strings.Join(resourceKeys, ",") == object.Annotations[common.ReplicatedKeysAnnotation] {
 		logger.Debugf("Deleting %s", targetLocation)
-		if err := r.Client.CoreV1().Secrets(object.Namespace).Delete(context.TODO(), object.Name, metav1.DeleteOptions{}); err != nil {
+		if err := r.Client.CoreV1().ConfigMaps(object.Namespace).Delete(context.TODO(), object.Name, metav1.DeleteOptions{}); err != nil {
```
Comment (martin-helmich) [inline replicate/configmap/configmaps.go:275]: Ouch... I don't believe it... 🤦  Good catch! :+1:

File: replicate/common/generic-replicator.go [hunk 2]
```diff
@@ -117,7 +117,7 @@ func (r *GenericReplicator) IsReplicationPermitted(object *metav1.ObjectMeta, so
 	allowedNamespaces := strings.Split(annotationAllowedNamespaces, ",")
 	allowed := false
 	for _, ns := range allowedNamespaces {
-		ns := strings.TrimSpace(ns)
+		ns := fmt.Sprintf("^%s$", strings.TrimSpace(ns))
```
Comment (martin-helmich) [inline replicate/common/generic-replicator.go:120]: Just a quick thought: What if someone _already_ specified a regex with start and/or end markers in their annotation (e.g. `replicator.v1.mittwald.de/replicate-to: "^my-ns-1$"`)? In this case, this would compile to a regex like `^^my-ns-1$$`. Maybe we should add a workaround for this?

```go
s = strings.TrimSpace(s)

if !strings.HasPrefix(s, "^") {
    s = "^" + s
}

if !strings.HasSuffix(s, "$") {
    s = s + "$"
}
```

❓

File: replicate/common/strings.go [hunk 3]
```diff
@@ -59,7 +59,7 @@ func MustGetObject(obj interface{}) metav1.Object {
 
 func StringToPatternList(list string) (result []*regexp.Regexp) {
 	for _, s := range strings.Split(list, ",") {
-		s = strings.TrimSpace(s)
+		s = fmt.Sprintf("^%s$", strings.TrimSpace(s))
```
Comment (martin-helmich) [inline replicate/common/strings.go:62]: Duplicate code. Can we extract the regex-building into its own function?

**Review by martin-helmich — CHANGES_REQUESTED** [review]
:+1: in general with a few minor nitpicks/thoughts. In general, also please try to keep fixes for separate issues in separate PRs.

File: replicate/common/generic-replicator.go (hunk 2 above)
Comment (YannikBramkamp) [reply replicate/common/generic-replicator.go:120]: From testing on go playground it doesn't look like it causes issues, i.e. ```^^my-ns-1$$``` still matches ```my-ns-1```, but I'll add it to the dedicated regex-building function to be on the safe side

**Review by martin-helmich — DISMISSED** [review]
:+1: LGTM -- given the existing merge conflicts are resolved, I'd be ready to merge this.

**Review by martin-helmich — APPROVED** [review]

**Comment by veophi** [comment]
This idea sounds very good!  I want to know whether this deletion logic is implemented? Thanks a lot!
