### PR TITLE
Delete replicated keys when source Secret/Resource is deleted

### LINKED ISSUE #73: Replicated keys do not get removed when source is deleted
**Describe the bug**
If a manually generated secret or resource receives keys via ```replicate-to```, the replicated keys are not removed upon deletion of the source secret.

**To Reproduce**
Manually generated resource:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  namespace: test
  annotations:
data:
  test: "45"
```
Source resource:
```
aapiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  annotations:
    replicator.v1.mittwald.de/replicate-to: "test"
data:
  test_data: "3"
```
Replication:
```
$ kubectl create namespace test
$ kubectl apply -f manual.yaml
$ kubectl apply -f source.yaml
$ kubectl delete configmap-test
$ kubectl get configmap configmap-test -n test -o yaml
apiVersion: v1
data:
  test: "45"
  test_data: "3"
```

**Expected behavior**
The key```test_data``` gets removed upon deletion of the source resource.

**Environment:**
 - Kubernetes version: [1.19]
 - kubernetes-replicator version: [v2.5.1]

### PR DESCRIPTION
**Pull request by YannikBramkamp**
fixes #73

### CODE REVIEW

File: replicate/configmap/configmaps.go [hunk 1]
```diff
@@ -276,6 +276,29 @@ func (r *Replicator) DeleteReplicatedResource(targetResource interface{}) error
...
+		exists := make(map[string]struct{})
+		for _, value := range resourceKeys {
+			exists[value] = struct{}{}
+		}
+		for _, val := range strings.Split(object.Annotations[common.ReplicatedKeysAnnotation], ",") {
+			if _, ok := exists[val]; ok {
+				patch = append(patch, common.JSONPatchOperation{Operation: "remove", Path: fmt.Sprintf("/data/%s", val)})
+			}
+		}
+		patch = append(patch, common.JSONPatchOperation{Operation: "remove", Path: fmt.Sprintf("/metadata/annotations/%s", strings.Replace(common.ReplicatedKeysAnnotation, "/", "~1", 1))})
```
Comment (hensur) [inline replicate/configmap/configmaps.go:289]: I think it would be useful to move this to a common method like `common.JSONPatchPathEscape()`. This would require the `Replace` to handle all occurrences of a given character.

Comment (YannikBramkamp) [reply replicate/configmap/configmaps.go]: Added the function in common.go.
Found an issue when a resource inherits from multiple sources, since the entire annotation gets deleted, so I'll rework it to update the annotation instead

**Review by hensur — APPROVED** [review]
